/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiVisibilityRouteImport } from './routes/ai-visibility'
import { Route as CompetitorsRouteImport } from './routes/competitors'
import { Route as ContextRouteImport } from './routes/context'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as ProvenanceRouteImport } from './routes/provenance'
import { Route as QueriesRouteImport } from './routes/queries'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiVisibilityRoute = AiVisibilityRouteImport.update({
  id: '/ai-visibility',
  path: '/ai-visibility',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsRoute = CompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextRoute = ContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvenanceRoute = ProvenanceRouteImport.update({
  id: '/provenance',
  path: '/provenance',
  getParentRoute: () => rootRouteImport,
} as any)
const QueriesRoute = QueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-visibility': typeof AiVisibilityRoute
  '/competitors': typeof CompetitorsRoute
  '/context': typeof ContextRoute
  '/decisions': typeof DecisionsRoute
  '/experiments': typeof ExperimentsRoute
  '/provenance': typeof ProvenanceRoute
  '/queries': typeof QueriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-visibility': typeof AiVisibilityRoute
  '/competitors': typeof CompetitorsRoute
  '/context': typeof ContextRoute
  '/decisions': typeof DecisionsRoute
  '/experiments': typeof ExperimentsRoute
  '/provenance': typeof ProvenanceRoute
  '/queries': typeof QueriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-visibility': typeof AiVisibilityRoute
  '/competitors': typeof CompetitorsRoute
  '/context': typeof ContextRoute
  '/decisions': typeof DecisionsRoute
  '/experiments': typeof ExperimentsRoute
  '/provenance': typeof ProvenanceRoute
  '/queries': typeof QueriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-visibility'
    | '/competitors'
    | '/context'
    | '/decisions'
    | '/experiments'
    | '/provenance'
    | '/queries'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-visibility'
    | '/competitors'
    | '/context'
    | '/decisions'
    | '/experiments'
    | '/provenance'
    | '/queries'
  id:
    | '__root__'
    | '/'
    | '/ai-visibility'
    | '/competitors'
    | '/context'
    | '/decisions'
    | '/experiments'
    | '/provenance'
    | '/queries'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiVisibilityRoute: typeof AiVisibilityRoute
  CompetitorsRoute: typeof CompetitorsRoute
  ContextRoute: typeof ContextRoute
  DecisionsRoute: typeof DecisionsRoute
  ExperimentsRoute: typeof ExperimentsRoute
  ProvenanceRoute: typeof ProvenanceRoute
  QueriesRoute: typeof QueriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-visibility': {
      id: '/ai-visibility'
      path: '/ai-visibility'
      fullPath: '/ai-visibility'
      preLoaderRoute: typeof AiVisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors': {
      id: '/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof CompetitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context': {
      id: '/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof ContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provenance': {
      id: '/provenance'
      path: '/provenance'
      fullPath: '/provenance'
      preLoaderRoute: typeof ProvenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queries': {
      id: '/queries'
      path: '/queries'
      fullPath: '/queries'
      preLoaderRoute: typeof QueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiVisibilityRoute: AiVisibilityRoute,
  CompetitorsRoute: CompetitorsRoute,
  ContextRoute: ContextRoute,
  DecisionsRoute: DecisionsRoute,
  ExperimentsRoute: ExperimentsRoute,
  ProvenanceRoute: ProvenanceRoute,
  QueriesRoute: QueriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
