/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAiVisibilityRouteImport } from './routes/_authenticated/ai-visibility'
import { Route as AuthenticatedCompetitorsRouteImport } from './routes/_authenticated/competitors'
import { Route as AuthenticatedContextRouteImport } from './routes/_authenticated/context'
import { Route as AuthenticatedDecisionsRouteImport } from './routes/_authenticated/decisions'
import { Route as AuthenticatedExperimentsRouteImport } from './routes/_authenticated/experiments'
import { Route as AuthenticatedLocalSeoRouteImport } from './routes/_authenticated/local-seo'
import { Route as AuthenticatedMeasurementRouteImport } from './routes/_authenticated/measurement'
import { Route as AuthenticatedModulesRouteImport } from './routes/_authenticated/modules'
import { Route as AuthenticatedProvenanceRouteImport } from './routes/_authenticated/provenance'
import { Route as AuthenticatedQueriesRouteImport } from './routes/_authenticated/queries'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiVisibilityRoute =
  AuthenticatedAiVisibilityRouteImport.update({
    id: '/ai-visibility',
    path: '/ai-visibility',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompetitorsRoute =
  AuthenticatedCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContextRoute = AuthenticatedContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDecisionsRoute = AuthenticatedDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExperimentsRoute =
  AuthenticatedExperimentsRouteImport.update({
    id: '/experiments',
    path: '/experiments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLocalSeoRoute = AuthenticatedLocalSeoRouteImport.update({
  id: '/local-seo',
  path: '/local-seo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeasurementRoute =
  AuthenticatedMeasurementRouteImport.update({
    id: '/measurement',
    path: '/measurement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulesRoute = AuthenticatedModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProvenanceRoute = AuthenticatedProvenanceRouteImport.update({
  id: '/provenance',
  path: '/provenance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQueriesRoute = AuthenticatedQueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/ai-visibility': typeof AuthenticatedAiVisibilityRoute
  '/competitors': typeof AuthenticatedCompetitorsRoute
  '/context': typeof AuthenticatedContextRoute
  '/decisions': typeof AuthenticatedDecisionsRoute
  '/experiments': typeof AuthenticatedExperimentsRoute
  '/local-seo': typeof AuthenticatedLocalSeoRoute
  '/measurement': typeof AuthenticatedMeasurementRoute
  '/modules': typeof AuthenticatedModulesRoute
  '/provenance': typeof AuthenticatedProvenanceRoute
  '/queries': typeof AuthenticatedQueriesRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/ai-visibility': typeof AuthenticatedAiVisibilityRoute
  '/competitors': typeof AuthenticatedCompetitorsRoute
  '/context': typeof AuthenticatedContextRoute
  '/decisions': typeof AuthenticatedDecisionsRoute
  '/experiments': typeof AuthenticatedExperimentsRoute
  '/local-seo': typeof AuthenticatedLocalSeoRoute
  '/measurement': typeof AuthenticatedMeasurementRoute
  '/modules': typeof AuthenticatedModulesRoute
  '/provenance': typeof AuthenticatedProvenanceRoute
  '/queries': typeof AuthenticatedQueriesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ai-visibility': typeof AuthenticatedAiVisibilityRoute
  '/_authenticated/competitors': typeof AuthenticatedCompetitorsRoute
  '/_authenticated/context': typeof AuthenticatedContextRoute
  '/_authenticated/decisions': typeof AuthenticatedDecisionsRoute
  '/_authenticated/experiments': typeof AuthenticatedExperimentsRoute
  '/_authenticated/local-seo': typeof AuthenticatedLocalSeoRoute
  '/_authenticated/measurement': typeof AuthenticatedMeasurementRoute
  '/_authenticated/modules': typeof AuthenticatedModulesRoute
  '/_authenticated/provenance': typeof AuthenticatedProvenanceRoute
  '/_authenticated/queries': typeof AuthenticatedQueriesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai-visibility'
    | '/competitors'
    | '/context'
    | '/decisions'
    | '/experiments'
    | '/local-seo'
    | '/measurement'
    | '/modules'
    | '/provenance'
    | '/queries'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/ai-visibility'
    | '/competitors'
    | '/context'
    | '/decisions'
    | '/experiments'
    | '/local-seo'
    | '/measurement'
    | '/modules'
    | '/provenance'
    | '/queries'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ai-visibility'
    | '/_authenticated/competitors'
    | '/_authenticated/context'
    | '/_authenticated/decisions'
    | '/_authenticated/experiments'
    | '/_authenticated/local-seo'
    | '/_authenticated/measurement'
    | '/_authenticated/modules'
    | '/_authenticated/provenance'
    | '/_authenticated/queries'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-visibility': {
      id: '/_authenticated/ai-visibility'
      path: '/ai-visibility'
      fullPath: '/ai-visibility'
      preLoaderRoute: typeof AuthenticatedAiVisibilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competitors': {
      id: '/_authenticated/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof AuthenticatedCompetitorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/context': {
      id: '/_authenticated/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof AuthenticatedContextRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decisions': {
      id: '/_authenticated/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof AuthenticatedDecisionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experiments': {
      id: '/_authenticated/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof AuthenticatedExperimentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/local-seo': {
      id: '/_authenticated/local-seo'
      path: '/local-seo'
      fullPath: '/local-seo'
      preLoaderRoute: typeof AuthenticatedLocalSeoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/measurement': {
      id: '/_authenticated/measurement'
      path: '/measurement'
      fullPath: '/measurement'
      preLoaderRoute: typeof AuthenticatedMeasurementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules': {
      id: '/_authenticated/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof AuthenticatedModulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provenance': {
      id: '/_authenticated/provenance'
      path: '/provenance'
      fullPath: '/provenance'
      preLoaderRoute: typeof AuthenticatedProvenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/queries': {
      id: '/_authenticated/queries'
      path: '/queries'
      fullPath: '/queries'
      preLoaderRoute: typeof AuthenticatedQueriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiVisibilityRoute: typeof AuthenticatedAiVisibilityRoute
  AuthenticatedCompetitorsRoute: typeof AuthenticatedCompetitorsRoute
  AuthenticatedContextRoute: typeof AuthenticatedContextRoute
  AuthenticatedDecisionsRoute: typeof AuthenticatedDecisionsRoute
  AuthenticatedExperimentsRoute: typeof AuthenticatedExperimentsRoute
  AuthenticatedLocalSeoRoute: typeof AuthenticatedLocalSeoRoute
  AuthenticatedMeasurementRoute: typeof AuthenticatedMeasurementRoute
  AuthenticatedModulesRoute: typeof AuthenticatedModulesRoute
  AuthenticatedProvenanceRoute: typeof AuthenticatedProvenanceRoute
  AuthenticatedQueriesRoute: typeof AuthenticatedQueriesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiVisibilityRoute: AuthenticatedAiVisibilityRoute,
  AuthenticatedCompetitorsRoute: AuthenticatedCompetitorsRoute,
  AuthenticatedContextRoute: AuthenticatedContextRoute,
  AuthenticatedDecisionsRoute: AuthenticatedDecisionsRoute,
  AuthenticatedExperimentsRoute: AuthenticatedExperimentsRoute,
  AuthenticatedLocalSeoRoute: AuthenticatedLocalSeoRoute,
  AuthenticatedMeasurementRoute: AuthenticatedMeasurementRoute,
  AuthenticatedModulesRoute: AuthenticatedModulesRoute,
  AuthenticatedProvenanceRoute: AuthenticatedProvenanceRoute,
  AuthenticatedQueriesRoute: AuthenticatedQueriesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
