// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import { ownerAuthStorage } from '../../lib/owner-session.storage';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

import {
  ensureSupabaseBrowserConfig,
  getSupabaseConfigError,
  readSupabaseBrowserConfig,
} from './public-config';

export { ensureSupabaseBrowserConfig, getSupabaseConfigError };

function createSupabaseClient() {
  const configError = getSupabaseConfigError();
  if (configError) {
    console.error(`[Supabase] ${configError}`);
    throw new Error(configError);
  }

  const { url, anonKey } = readSupabaseBrowserConfig();

  return createClient<Database>(url, anonKey, {
    global: {
      fetch: createSupabaseFetch(anonKey),
    },
    auth: {
      storage: ownerAuthStorage(brokeredPreviewStorage()),
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

